// Generated by gencpp from file pos_server/pos_service.msg
// DO NOT EDIT!


#ifndef POS_SERVER_MESSAGE_POS_SERVICE_H
#define POS_SERVER_MESSAGE_POS_SERVICE_H

#include <ros/service_traits.h>


#include <pos_server/pos_serviceRequest.h>
#include <pos_server/pos_serviceResponse.h>


namespace pos_server
{

struct pos_service
{

typedef pos_serviceRequest Request;
typedef pos_serviceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pos_service
} // namespace pos_server


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pos_server::pos_service > {
  static const char* value()
  {
    return "ff8d7d66dd3e4b731ef14a45d38888b6";
  }

  static const char* value(const ::pos_server::pos_service&) { return value(); }
};

template<>
struct DataType< ::pos_server::pos_service > {
  static const char* value()
  {
    return "pos_server/pos_service";
  }

  static const char* value(const ::pos_server::pos_service&) { return value(); }
};


// service_traits::MD5Sum< ::pos_server::pos_serviceRequest> should match 
// service_traits::MD5Sum< ::pos_server::pos_service > 
template<>
struct MD5Sum< ::pos_server::pos_serviceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pos_server::pos_service >::value();
  }
  static const char* value(const ::pos_server::pos_serviceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pos_server::pos_serviceRequest> should match 
// service_traits::DataType< ::pos_server::pos_service > 
template<>
struct DataType< ::pos_server::pos_serviceRequest>
{
  static const char* value()
  {
    return DataType< ::pos_server::pos_service >::value();
  }
  static const char* value(const ::pos_server::pos_serviceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pos_server::pos_serviceResponse> should match 
// service_traits::MD5Sum< ::pos_server::pos_service > 
template<>
struct MD5Sum< ::pos_server::pos_serviceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pos_server::pos_service >::value();
  }
  static const char* value(const ::pos_server::pos_serviceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pos_server::pos_serviceResponse> should match 
// service_traits::DataType< ::pos_server::pos_service > 
template<>
struct DataType< ::pos_server::pos_serviceResponse>
{
  static const char* value()
  {
    return DataType< ::pos_server::pos_service >::value();
  }
  static const char* value(const ::pos_server::pos_serviceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // POS_SERVER_MESSAGE_POS_SERVICE_H
