// Generated by gencpp from file pos_server/pos_serviceRequest.msg
// DO NOT EDIT!


#ifndef POS_SERVER_MESSAGE_POS_SERVICEREQUEST_H
#define POS_SERVER_MESSAGE_POS_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace pos_server
{
template <class ContainerAllocator>
struct pos_serviceRequest_
{
  typedef pos_serviceRequest_<ContainerAllocator> Type;

  pos_serviceRequest_()
    {
    }
  pos_serviceRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::pos_server::pos_serviceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::pos_server::pos_serviceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct pos_serviceRequest_

typedef ::pos_server::pos_serviceRequest_<std::allocator<void> > pos_serviceRequest;

typedef boost::shared_ptr< ::pos_server::pos_serviceRequest > pos_serviceRequestPtr;
typedef boost::shared_ptr< ::pos_server::pos_serviceRequest const> pos_serviceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::pos_server::pos_serviceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::pos_server::pos_serviceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace pos_server

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::pos_server::pos_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::pos_server::pos_serviceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::pos_server::pos_serviceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::pos_server::pos_serviceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "pos_server/pos_serviceRequest";
  }

  static const char* value(const ::pos_server::pos_serviceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
";
  }

  static const char* value(const ::pos_server::pos_serviceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pos_serviceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::pos_server::pos_serviceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::pos_server::pos_serviceRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // POS_SERVER_MESSAGE_POS_SERVICEREQUEST_H
