// Generated by gencpp from file custom_messages/Sum.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_SUM_H
#define CUSTOM_MESSAGES_MESSAGE_SUM_H

#include <ros/service_traits.h>


#include <custom_messages/SumRequest.h>
#include <custom_messages/SumResponse.h>


namespace custom_messages
{

struct Sum
{

typedef SumRequest Request;
typedef SumResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Sum
} // namespace custom_messages


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_messages::Sum > {
  static const char* value()
  {
    return "210a18f816d5b88becb133b82fae0c4c";
  }

  static const char* value(const ::custom_messages::Sum&) { return value(); }
};

template<>
struct DataType< ::custom_messages::Sum > {
  static const char* value()
  {
    return "custom_messages/Sum";
  }

  static const char* value(const ::custom_messages::Sum&) { return value(); }
};


// service_traits::MD5Sum< ::custom_messages::SumRequest> should match 
// service_traits::MD5Sum< ::custom_messages::Sum > 
template<>
struct MD5Sum< ::custom_messages::SumRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_messages::Sum >::value();
  }
  static const char* value(const ::custom_messages::SumRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_messages::SumRequest> should match 
// service_traits::DataType< ::custom_messages::Sum > 
template<>
struct DataType< ::custom_messages::SumRequest>
{
  static const char* value()
  {
    return DataType< ::custom_messages::Sum >::value();
  }
  static const char* value(const ::custom_messages::SumRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_messages::SumResponse> should match 
// service_traits::MD5Sum< ::custom_messages::Sum > 
template<>
struct MD5Sum< ::custom_messages::SumResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_messages::Sum >::value();
  }
  static const char* value(const ::custom_messages::SumResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_messages::SumResponse> should match 
// service_traits::DataType< ::custom_messages::Sum > 
template<>
struct DataType< ::custom_messages::SumResponse>
{
  static const char* value()
  {
    return DataType< ::custom_messages::Sum >::value();
  }
  static const char* value(const ::custom_messages::SumResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_SUM_H
