// Generated by gencpp from file custom_messages/SumResponse.msg
// DO NOT EDIT!


#ifndef CUSTOM_MESSAGES_MESSAGE_SUMRESPONSE_H
#define CUSTOM_MESSAGES_MESSAGE_SUMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_messages
{
template <class ContainerAllocator>
struct SumResponse_
{
  typedef SumResponse_<ContainerAllocator> Type;

  SumResponse_()
    : sum(0.0)  {
    }
  SumResponse_(const ContainerAllocator& _alloc)
    : sum(0.0)  {
  (void)_alloc;
    }



   typedef float _sum_type;
  _sum_type sum;





  typedef boost::shared_ptr< ::custom_messages::SumResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_messages::SumResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SumResponse_

typedef ::custom_messages::SumResponse_<std::allocator<void> > SumResponse;

typedef boost::shared_ptr< ::custom_messages::SumResponse > SumResponsePtr;
typedef boost::shared_ptr< ::custom_messages::SumResponse const> SumResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_messages::SumResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_messages::SumResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_messages

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'custom_messages': ['/home/my_ros/src/custom_messages/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::SumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_messages::SumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::SumResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_messages::SumResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::SumResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_messages::SumResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_messages::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f720a7bfc448e377e8e2dd877c1aef43";
  }

  static const char* value(const ::custom_messages::SumResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf720a7bfc448e377ULL;
  static const uint64_t static_value2 = 0xe8e2dd877c1aef43ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_messages::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_messages/SumResponse";
  }

  static const char* value(const ::custom_messages::SumResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_messages::SumResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 sum\n\
\n\
";
  }

  static const char* value(const ::custom_messages::SumResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_messages::SumResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.sum);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SumResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_messages::SumResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_messages::SumResponse_<ContainerAllocator>& v)
  {
    s << indent << "sum: ";
    Printer<float>::stream(s, indent + "  ", v.sum);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_MESSAGES_MESSAGE_SUMRESPONSE_H
